# Generated by Django 4.2.11 on 2024-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=50)),
                ('actividadEconomica', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('ingresos', models.FloatField()),
                ('deudas', models.FloatField()),
            ],
        ),
    ]
